### PR TITLE
[feature] reCAPTCHA solver and cookies reusing are supported

### PR DESCRIPTION
**Pull request by DevRoss**
A new auth_type, which can solve simple reCAPTCHA.
testing:
```python
ChatGPT(email='your_email', password='your_password', auth_type='openai')
```

- [x] reCAPTCHA v1
- [x] reCAPTCHA enterprise. 
- [x] reuse login cookies

### CODE REVIEW

**Comment by terry3041** [comment]
Looks good to me. Though I don't have much time to test this.
I will merge this few days after my exam.

**Comment by DevRoss** [comment]
Good news for new commits:
1. I solved  the reCAPTCHA enterprise challenge by using 2captcha api, now it can log in without human interaction.
2. fix bug for checking error response.

**Comment by DevRoss** [comment]
Reuse login cookies:
```python
ChatGPT(auth_type='openai', email='example@xxx.com', password='password',
               twocaptcha_apikey='your_twocaptcha_apikey' , login_cookies_path='your_cookies_path',
               verbose=True)

ChatGPT(auth_type='google', email='example@gamil.com', password='password',
               login_cookies_path='your_cookies_path', verbose=True)
```

**Comment by terry3041** [comment]
Looks good to me.

**Pull request merged**
